# Generated by Django 5.2.4 on 2025-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_product', to='shop.order'),
        ),
    ]
