# Generated by Django 5.2.4 on 2025-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(related_name='order_product', to='shop.order'),
        ),
    ]
