# Generated by Django 5.2.4 on 2025-07-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_product', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='shop.favorite'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='order_product', to='shop.order'),
        ),
    ]
