# Generated by Django 5.2.5 on 2025-08-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart_order', to='shop.cart'),
        ),
    ]
