# Generated by Django 5.2.5 on 2025-08-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_is_active_alter_order_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
