# Generated by Django 5.2.5 on 2025-08-30 18:55

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_tags_delete_tag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='product_images/'),
        ),
    ]
